# Generated by Django 5.2.17 on 2026-09-16 08:11

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lead_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('vertical', models.CharField(choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, default='REGULAR', max_length=30)),
                ('channel', models.CharField(choices=[('DIRECT', 'BEST Direct'), ('PARTNER', 'Partner')], db_index=True, default='DIRECT', max_length=20)),
                ('source', models.CharField(blank=True, help_text='Example: Facebook, Instagram, Website, Walk-in, Referral', max_length=100)),
                ('campaign', models.CharField(blank=True, max_length=150)),
                ('interested_course', models.CharField(blank=True, max_length=200)),
                ('previous_course', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('FOLLOW_UP', 'Follow Up'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=30)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('CALLBACK', 'Call Back'), ('NO_ANSWER', 'No Answer'), ('BUSY', 'Busy'), ('WRONG_NUMBER', 'Wrong Number'), ('SWITCHED_OFF', 'Switched Off'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('called_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('follow_up_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional manual call duration in seconds.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('telecaller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='leads.lead')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CALL', 'Call'), ('NOTE', 'Note'), ('FOLLOW_UP', 'Follow Up'), ('STATUS_CHANGE', 'Status Change'), ('CONVERTED', 'Converted')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status', 'assigned_to'], name='leads_lead_status_a53442_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['vertical', 'status'], name='leads_lead_vertica_867d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['channel', 'status'], name='leads_lead_channel_c08448_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['lead', 'called_at'], name='leads_calll_lead_id_f4d9b0_idx'),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['telecaller', 'outcome'], name='leads_calll_telecal_885361_idx'),
        ),
    ]
