# Generated by Django 5.2.17 on 2026-09-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='calllog',
            name='leads_calll_telecal_885361_idx',
        ),
        migrations.AddField(
            model_name='lead',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='partners.partner'),
        ),
        migrations.AddField(
            model_name='lead',
            name='partner_reference_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='alternate_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='interested_course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='previous_course',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CALL', 'Call'), ('NOTE', 'Note'), ('FOLLOW_UP', 'Follow Up'), ('STATUS_CHANGE', 'Status Change'), ('CONVERTED', 'Converted')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name='calllog',
            index=models.Index(fields=['telecaller', 'called_at'], name='leads_calll_telecal_d7e2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['partner', 'status'], name='leads_lead_partner_917119_idx'),
        ),
    ]
