# Generated by Django 5.2.17 on 2026-09-24 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_program_counselling_master'),
        ('leads', '0003_leadimportbatch_leadimportrow'),
        ('organization', '0002_alter_department_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('ASSIGNED', 'Assigned'), ('CONTACTED', 'Contacted'), ('INTERESTED', 'Interested'), ('FOLLOW_UP', 'Follow Up'), ('QUALIFIED', 'Qualified'), ('CONVERTED', 'Converted'), ('NOT_INTERESTED', 'Not Interested'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=30),
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(choices=[('CREATED', 'Created'), ('ASSIGNED', 'Assigned'), ('CALL', 'Call'), ('NOTE', 'Note'), ('FOLLOW_UP', 'Follow Up'), ('QUALIFICATION', 'Qualification'), ('APPOINTMENT', 'Appointment'), ('STATUS_CHANGE', 'Status Change'), ('CONVERTED', 'Converted')], db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='LeadQualification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('highest_qualification', models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('SSLC', 'SSLC / 10th'), ('PLUS_TWO', 'Plus Two / 12th'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate Degree'), ('PG', 'Postgraduate Degree'), ('OTHER', 'Other')], db_index=True, default='UNSPECIFIED', max_length=30)),
                ('stream', models.CharField(blank=True, max_length=150)),
                ('board_or_university', models.CharField(blank=True, max_length=255)),
                ('year_of_passing', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage_or_grade', models.CharField(blank=True, max_length=50)),
                ('required_level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], db_index=True, default='UG', max_length=30)),
                ('interest_area', models.CharField(blank=True, max_length=255)),
                ('customer_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quoted_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('eligibility_status', models.CharField(choices=[('PENDING', 'Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('REVIEW_REQUIRED', 'Review Required')], db_index=True, default='PENDING', max_length=30)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('qualified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qualification', to='leads.lead')),
                ('qualified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qualified_leads', to=settings.AUTH_USER_MODEL)),
                ('selected_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_qualifications', to='admissions.institution')),
                ('selected_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_qualifications', to='admissions.program')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadAppointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('COUNSELLING', 'Counselling'), ('DOCUMENTS', 'Document Submission'), ('ADMISSION', 'Admission'), ('OTHER', 'Other')], default='COUNSELLING', max_length=30)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('number_of_visitors', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], db_index=True, default='SCHEDULED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_counsellor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_appointments', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_appointments', to='organization.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_lead_appointments', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='leads.lead')),
            ],
            options={
                'ordering': ['scheduled_at'],
                'indexes': [models.Index(fields=['lead', 'status'], name='leads_leada_lead_id_359bee_idx'), models.Index(fields=['scheduled_at', 'status'], name='leads_leada_schedul_1e4ad5_idx')],
            },
        ),
    ]
