# Generated by Django 5.2.17 on 2026-09-24 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_telecaller_counselling_appointments'),
        ('organization', '0002_alter_department_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAppointmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGE', 'Status Change'), ('RESCHEDULED', 'Rescheduled')], db_index=True, max_length=30)),
                ('previous_status', models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], max_length=30)),
                ('new_status', models.CharField(blank=True, choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('ARRIVED', 'Arrived'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], max_length=30)),
                ('previous_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('new_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='leadappointment',
            name='purpose',
            field=models.CharField(choices=[('ADMISSION_COUNSELLING', 'Admission Counselling'), ('COURSE_ENQUIRY', 'Course Enquiry'), ('UNIVERSITY_COURSE_SELECTION', 'University / Course Selection'), ('FEE_DISCUSSION', 'Fee Discussion'), ('DOCUMENT_SUBMISSION', 'Document Submission'), ('CREDIT_TRANSFER_DISCUSSION', 'Credit Transfer Discussion'), ('BACKLOG_COMPLETION_DISCUSSION', 'Backlog Completion Discussion'), ('ADMISSION_CONFIRMATION', 'Admission Confirmation'), ('OTHER', 'Other')], default='ADMISSION_COUNSELLING', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='leadappointment',
            constraint=models.CheckConstraint(condition=models.Q(('number_of_visitors__gte', 1)), name='lead_appointment_visitors_gte_1'),
        ),
        migrations.AddField(
            model_name='leadappointmenthistory',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.leadappointment'),
        ),
        migrations.AddField(
            model_name='leadappointmenthistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_appointment_history_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
