# Generated by Django 5.2.17 on 2026-09-16 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('academic_session', models.CharField(blank=True, max_length=50)),
                ('enrollment_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('university_admission_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('vertical', models.CharField(choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('DIRECT', 'BEST Direct'), ('PARTNER', 'Partner')], db_index=True, max_length=20)),
                ('current_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Course Completed'), ('DISCONTINUED', 'Discontinued'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACTIVE', max_length=30)),
                ('course_started_at', models.DateField(blank=True, null=True)),
                ('course_completed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='admissions.admission')),
                ('assigned_coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coordinated_students', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_students', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.institution')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='admissions.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Student Created'), ('PROCESS', 'Education Process'), ('STATUS_CHANGE', 'Status Change'), ('DOCUMENT', 'Document'), ('EXAM', 'Exam'), ('SEMINAR', 'Seminar'), ('PROJECT', 'Project'), ('RESULT', 'Result'), ('MARK_SHEET', 'Mark Sheet'), ('CERTIFICATE', 'Certificate'), ('NOTE', 'Note'), ('COURSE_COMPLETED', 'Course Completed')], db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_activities', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('process_type', models.CharField(choices=[('EXAM', 'Exam'), ('SEMINAR', 'Seminar'), ('PROJECT', 'Project'), ('RESULT', 'Result'), ('MARK_SHEET', 'Mark Sheet'), ('CERTIFICATE', 'Certificate')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('COMPLETED', 'Completed'), ('NOT_APPLICABLE', 'Not Applicable'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_STARTED', max_length=30)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_student_processes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='students.student')),
            ],
            options={
                'ordering': ['academic_year', 'semester', 'process_type'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('EXAM_APPLICATION', 'Exam Application'), ('HALL_TICKET', 'Hall Ticket'), ('SEMINAR', 'Seminar Document'), ('PROJECT', 'Project Document'), ('RESULT', 'Result'), ('MARK_SHEET', 'Mark Sheet'), ('PROVISIONAL', 'Provisional Certificate'), ('DEGREE_CERTIFICATE', 'Degree Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='students/documents/%Y/%m/')),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_student_documents', to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='students.studentprocess')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['status', 'assigned_coordinator'], name='students_st_status_b1ea16_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['institution', 'status'], name='students_st_institu_bf1ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['program', 'status'], name='students_st_program_56314d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprocess',
            index=models.Index(fields=['process_type', 'status'], name='students_st_process_233633_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprocess',
            index=models.Index(fields=['student', 'status'], name='students_st_student_715e46_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprocess',
            index=models.Index(fields=['assigned_to', 'status'], name='students_st_assigne_20df99_idx'),
        ),
    ]
