# Generated by Django 5.2.17 on 2026-09-23 04:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(default='BEST Education Operations & Intelligence System', max_length=150)),
                ('system_short_name', models.CharField(default='BEOIS', max_length=50)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=100)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('date_format', models.CharField(choices=[('DD-MM-YYYY', 'DD-MM-YYYY'), ('DD/MM/YYYY', 'DD/MM/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD-MM-YYYY', max_length=30)),
                ('financial_year_start_month', models.PositiveSmallIntegerField(default=4, help_text='1 = January, 4 = April, etc.')),
                ('lead_prefix', models.CharField(default='LD', max_length=10)),
                ('credit_transfer_prefix', models.CharField(default='CT', max_length=10)),
                ('admission_prefix', models.CharField(default='AD', max_length=10)),
                ('student_prefix', models.CharField(default='ST', max_length=10)),
                ('partner_prefix', models.CharField(default='BPT', max_length=10)),
                ('employee_prefix', models.CharField(default='EMP', max_length=10)),
                ('identifier_padding', models.PositiveSmallIntegerField(default=5, help_text='Number of digits after the prefix.')),
                ('default_callback_days', models.PositiveSmallIntegerField(default=1)),
                ('default_follow_up_days', models.PositiveSmallIntegerField(default=7)),
                ('default_academic_session', models.CharField(blank=True, max_length=50)),
                ('admission_document_reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('admission_fee_reminder_days', models.PositiveSmallIntegerField(default=3)),
                ('standard_working_minutes_per_day', models.PositiveIntegerField(default=480, help_text='Default: 480 minutes = 8 hours.')),
                ('attendance_grace_minutes', models.PositiveSmallIntegerField(default=15)),
                ('payroll_default_payment_method', models.CharField(default='BANK_TRANSFER', max_length=50)),
                ('maximum_upload_size_mb', models.PositiveIntegerField(default=10)),
                ('document_retention_days', models.PositiveIntegerField(default=3650, help_text='Default: approximately 10 years.')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('reminder_days_before_due_date', models.PositiveSmallIntegerField(default=3)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480, help_text='Administrative policy value. Authentication integration may use it later.')),
                ('require_mfa_for_management', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='SystemSettingsAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_fields', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='core.systemsettings')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
