# Generated by Django 5.2.17 on 2026-09-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='partner_case_prefix',
            field=models.CharField(default='PC', max_length=20),
        ),
    ]
