# Generated by Django 5.2.17 on 2026-09-16 11:54

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_alter_admissiondocument_options_and_more'),
        ('hr', '0004_salarycomponent_employeesalarystructure_payroll_and_more'),
        ('organization', '0002_alter_department_branch'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('category_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('bill_number', models.CharField(blank=True, max_length=100)),
                ('bill_date', models.DateField(blank=True, null=True)),
                ('expense_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organization.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organization.businessunit')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expenses_requested', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.transactioncategory')),
            ],
            options={
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('account_type', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('OTHER', 'Other')], max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=150)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('ifsc_code', models.CharField(blank=True, max_length=30)),
                ('upi_id', models.CharField(blank=True, max_length=150)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('opening_balance_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='organization.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_accounts', to='organization.businessunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('transaction_date', models.DateField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('ADMISSION_PAYMENT', 'Admission Payment'), ('UNIVERSITY_PAYMENT', 'University Payment'), ('PARTNER_COMMISSION', 'Partner Commission'), ('PAYROLL', 'Payroll'), ('EXPENSE', 'Operational Expense'), ('OTHER', 'Other')], default='MANUAL', max_length=30)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.financialaccount')),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='admissions.admission')),
                ('admission_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction', to='admissions.admissionpayment')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='organization.branch')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='organization.businessunit')),
                ('commission_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction', to='partners.commissiontransaction')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='admissions.institution')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_transactions', to='partners.partner')),
                ('payroll', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_transaction', to='hr.payroll')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_transactions_posted', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.transactioncategory')),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.expense')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_expense_payments', to=settings.AUTH_USER_MODEL)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to='finance.financialaccount')),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_payment', to='finance.financialtransaction')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityPayable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payable_number', models.CharField(blank=True, max_length=30, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payable_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_payables', to='admissions.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_payables_created', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finance_payables', to='admissions.institution')),
            ],
            options={
                'ordering': ['-payable_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('POSTED', 'Posted'), ('PAYMENT', 'Payment'), ('PARTIAL_PAYMENT', 'Partial Payment'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NOTE', 'Note'), ('SYNC', 'Source Sync')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.expense')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finance_activities', to=settings.AUTH_USER_MODEL)),
                ('financial_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.financialtransaction')),
                ('university_payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='finance.universitypayable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UniversityPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_at', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='university_payments', to='finance.financialaccount')),
                ('finance_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='university_payment', to='finance.financialtransaction')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_payments_made', to=settings.AUTH_USER_MODEL)),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.universitypayable')),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='fin_account_type_idx'),
        ),
        migrations.AddIndex(
            model_name='financialaccount',
            index=models.Index(fields=['branch', 'is_active'], name='fin_account_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['transaction_date', 'transaction_type'], name='fin_txn_date_type_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['account', 'status'], name='fin_txn_account_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['source_type', 'status'], name='fin_txn_source_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['branch', 'transaction_date'], name='fin_txn_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['admission', 'transaction_date'], name='fin_txn_admission_idx'),
        ),
        migrations.AddIndex(
            model_name='financialtransaction',
            index=models.Index(fields=['partner', 'transaction_date'], name='fin_txn_partner_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['status', 'expense_date'], name='fin_exp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'expense_date'], name='fin_exp_branch_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['due_date', 'status'], name='fin_exp_due_idx'),
        ),
        migrations.AddIndex(
            model_name='universitypayable',
            index=models.Index(fields=['institution', 'status'], name='fin_univ_inst_idx'),
        ),
        migrations.AddIndex(
            model_name='universitypayable',
            index=models.Index(fields=['admission', 'status'], name='fin_univ_adm_idx'),
        ),
        migrations.AddIndex(
            model_name='universitypayable',
            index=models.Index(fields=['due_date', 'status'], name='fin_univ_due_idx'),
        ),
        migrations.AddIndex(
            model_name='financeactivity',
            index=models.Index(fields=['financial_transaction', 'created_at'], name='fin_act_txn_idx'),
        ),
        migrations.AddIndex(
            model_name='financeactivity',
            index=models.Index(fields=['expense', 'created_at'], name='fin_act_exp_idx'),
        ),
        migrations.AddIndex(
            model_name='financeactivity',
            index=models.Index(fields=['university_payable', 'created_at'], name='fin_act_univ_idx'),
        ),
    ]
