# Generated by Django 5.2.17 on 2026-09-16 09:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partner_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('partner_type', models.CharField(choices=[('EDUCATION_CENTRE', 'Education Centre'), ('CONSULTANT', 'Education Consultant'), ('INDIVIDUAL', 'Individual Partner'), ('INSTITUTION', 'Institutional Partner'), ('OTHER', 'Other')], default='EDUCATION_CENTRE', max_length=30)),
                ('status', models.CharField(choices=[('PROSPECT', 'Prospect'), ('ONBOARDING', 'Onboarding'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('TERMINATED', 'Terminated')], db_index=True, default='PROSPECT', max_length=30)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, db_index=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('territory', models.CharField(blank=True, db_index=True, max_length=150)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=30)),
                ('pan_number', models.CharField(blank=True, max_length=30)),
                ('aadhaar_number', models.CharField(blank=True, max_length=20)),
                ('agreement_start_date', models.DateField(blank=True, null=True)),
                ('agreement_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_partners', to=settings.AUTH_USER_MODEL)),
                ('relationship_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vertical', models.CharField(blank=True, choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, max_length=30)),
                ('commission_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_commission_rules', to='admissions.institution')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_commission_rules', to='admissions.program')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='partners.partner')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Partner Created'), ('STATUS_CHANGE', 'Status Change'), ('DOCUMENT', 'Document'), ('AGREEMENT', 'Agreement'), ('PROGRAM_ACCESS', 'Program Access'), ('CASE', 'Student Case'), ('COMMISSION', 'Commission'), ('PAYMENT', 'Payment'), ('ISSUE', 'Issue'), ('NOTE', 'Note')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='partners.partner')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('case_id', models.CharField(blank=True, editable=False, max_length=25, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('vertical', models.CharField(choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, default='REGULAR', max_length=30)),
                ('partner_reference_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('ADMISSION_CREATED', 'Admission Created'), ('ENROLLED', 'Enrolled'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='RECEIVED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_case', to='admissions.admission')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_partner_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_partner_cases', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_cases', to='admissions.institution')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cases', to='partners.partner')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_cases', to='admissions.program')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('EARNED', 'Earned'), ('APPROVED', 'Approved'), ('PAYABLE', 'Payable'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], db_index=True, default='EARNED', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_commissions', to='admissions.admission')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_partner_commissions', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='partners.commissionrule')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_transactions', to='partners.partner')),
                ('partner_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commission_transactions', to='partners.partnercase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN Card'), ('GST', 'GST Certificate'), ('BUSINESS_PROOF', 'Business Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('BANK_PROOF', 'Bank Proof'), ('AGREEMENT', 'Agreement'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='partners/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.partner')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_partner_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_partner_issues', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='partners.partner')),
                ('partner_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='partners.partnercase')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerProgramAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_access', to='admissions.institution')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_access', to='partners.partner')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partner_access', to='admissions.program')),
            ],
            options={
                'ordering': ['partner', 'institution', 'program'],
            },
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['status', 'relationship_manager'], name='partners_pa_status_9147b9_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['state', 'city'], name='partners_pa_state_c79ffd_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['partner', 'is_active'], name='partners_co_partner_c16a99_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercase',
            index=models.Index(fields=['partner', 'status'], name='partners_pa_partner_4bdf54_idx'),
        ),
        migrations.AddIndex(
            model_name='partnercase',
            index=models.Index(fields=['status', 'assigned_to'], name='partners_pa_status_39af95_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['partner', 'status'], name='partners_co_partner_834b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='commissiontransaction',
            index=models.Index(fields=['status', 'created_at'], name='partners_co_status_1cfc36_idx'),
        ),
        migrations.AddIndex(
            model_name='partnerissue',
            index=models.Index(fields=['status', 'priority'], name='partners_pa_status_ab6946_idx'),
        ),
        migrations.AddConstraint(
            model_name='partnerprogramaccess',
            constraint=models.UniqueConstraint(fields=('partner', 'institution', 'program'), name='unique_partner_program_access'),
        ),
    ]
