# Generated by Django 5.2.17 on 2026-09-16 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_designation_employee_date_of_exit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_days_per_year', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_paid', models.BooleanField(default=True)),
                ('carry_forward_allowed', models.BooleanField(default=False)),
                ('maximum_carry_forward', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('LATE', 'Late'), ('WORK_FROM_HOME', 'Work From Home'), ('ON_LEAVE', 'On Leave'), ('HOLIDAY', 'Holiday'), ('WEEK_OFF', 'Week Off')], default='PRESENT', max_length=30)),
                ('check_in', models.DateTimeField(blank=True, null=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('working_minutes', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('overtime_minutes', models.PositiveIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('is_manually_adjusted', models.BooleanField(default=False)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjusted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_adjustments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__employee_id'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_att_emp_date_idx'), models.Index(fields=['date', 'status'], name='hr_att_date_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date'), name='unique_employee_daily_attendance')],
            },
        ),
        migrations.CreateModel(
            name='HRActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('ATTENDANCE', 'Attendance'), ('ATTENDANCE_ADJUSTMENT', 'Attendance Adjustment'), ('LEAVE_REQUEST', 'Leave Request'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_CANCELLED', 'Leave Cancelled'), ('LEAVE_BALANCE', 'Leave Balance'), ('NOTE', 'Note')], max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hr_activities', to='hr.employee')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_hr_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'created_at'], name='hr_activity_emp_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('day_type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('FIRST_HALF', 'First Half'), ('SECOND_HALF', 'Second Half')], default='FULL_DAY', max_length=20)),
                ('requested_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_requests', to='hr.leavetype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'status'], name='hr_leave_emp_status_idx'), models.Index(fields=['start_date', 'end_date'], name='hr_leave_dates_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeaveBalance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('allocated_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('adjusted_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_balances', to='hr.leavetype')),
            ],
            options={
                'ordering': ['-year', 'employee__employee_id', 'leave_type__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_employee_leave_balance')],
            },
        ),
    ]
