# Generated by Django 5.2.17 on 2026-09-16 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_leavetype_attendance_hractivity_leaverequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage')], default='FIXED', max_length=20)),
                ('is_taxable', models.BooleanField(default=False)),
                ('affects_gross_salary', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['component_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard Salary Structure', max_length=150)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_salary_structures', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structures', to='hr.employee')),
            ],
            options={
                'ordering': ['employee__employee_id', '-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('calendar_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payable_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('present_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('paid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('unpaid_leave_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('lop_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lop_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculated_payrolls', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employee')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payrolls', to=settings.AUTH_USER_MODEL)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.employeesalarystructure')),
            ],
            options={
                'ordering': ['-period__year', '-period__month', 'employee__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='PayrollActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('CALCULATED', 'Calculated'), ('RECALCULATED', 'Recalculated'), ('COMPONENT_ADDED', 'Component Added'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('ADVANCE_RECOVERY', 'Advance Recovery'), ('NOTE', 'Note')], max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='hr.payroll')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_payroll_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PROCESSING', 'Processing'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_payroll_periods', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payroll_periods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.AddField(
            model_name='payroll',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='hr.payrollperiod'),
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recovered_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_recovery_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('PARTIALLY_RECOVERED', 'Partially Recovered'), ('RECOVERED', 'Recovered'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=30)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_salary_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advances', to='hr.employee')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_salary_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('component_type', models.CharField(choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction')], max_length=20)),
                ('source_type', models.CharField(choices=[('SALARY_STRUCTURE', 'Salary Structure'), ('INCENTIVE', 'Incentive'), ('BONUS', 'Bonus'), ('MANUAL', 'Manual Adjustment'), ('LOP', 'Loss of Pay'), ('ADVANCE', 'Advance Recovery')], default='SALARY_STRUCTURE', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.payroll')),
                ('salary_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_components', to='hr.salarycomponent')),
            ],
            options={
                'ordering': ['component_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSalaryComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('salary_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='hr.employeesalarystructure')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_salary_components', to='hr.salarycomponent')),
            ],
            options={
                'ordering': ['component__component_type', 'component__name'],
            },
        ),
        migrations.AddIndex(
            model_name='employeesalarystructure',
            index=models.Index(fields=['employee', 'is_active', 'effective_from'], name='hr_salary_struct_emp_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollactivity',
            index=models.Index(fields=['payroll', 'created_at'], name='hr_payactivity_idx'),
        ),
        migrations.AddConstraint(
            model_name='payrollperiod',
            constraint=models.UniqueConstraint(fields=('year', 'month'), name='unique_payroll_year_month'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['employee', 'status'], name='hr_payroll_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payroll',
            index=models.Index(fields=['period', 'status'], name='hr_payroll_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='payroll',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='unique_employee_period_payroll'),
        ),
        migrations.AddIndex(
            model_name='salaryadvance',
            index=models.Index(fields=['employee', 'status'], name='hr_advance_emp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='payrollcomponent',
            index=models.Index(fields=['payroll', 'component_type'], name='hr_paycomp_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeesalarycomponent',
            constraint=models.UniqueConstraint(fields=('salary_structure', 'component'), name='unique_salary_structure_component'),
        ),
    ]
