# Generated by Django 5.2.17 on 2026-09-16 08:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('contact_person', models.CharField(blank=True, max_length=150)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('admission_id', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('applicant_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(db_index=True, max_length=30)),
                ('alternate_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('academic_session', models.CharField(blank=True, help_text='Example: 2026-27', max_length=50)),
                ('vertical', models.CharField(choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('DIRECT', 'BEST Direct'), ('PARTNER', 'Partner')], db_index=True, max_length=20)),
                ('partner_reference', models.CharField(blank=True, max_length=100)),
                ('previous_institution', models.CharField(blank=True, max_length=255)),
                ('previous_program', models.CharField(blank=True, max_length=255)),
                ('previous_registration_number', models.CharField(blank=True, max_length=100)),
                ('completed_years_or_semesters', models.CharField(blank=True, max_length=100)),
                ('credit_transfer_notes', models.TextField(blank=True)),
                ('university_application_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('enrollment_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('university_admission_number', models.CharField(blank=True, max_length=100)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('DOCUMENT_PENDING', 'Document Pending'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('ELIGIBILITY_PENDING', 'Eligibility Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('FEE_PENDING', 'Fee Pending'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied to Institution'), ('ENROLLMENT_PENDING', 'Enrollment Pending'), ('COMPLETED', 'Admission Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=40)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_admissions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_admissions', to=settings.AUTH_USER_MODEL)),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission', to='leads.lead')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='admissions.institution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('CREATED', 'Created'), ('STATUS_CHANGE', 'Status Change'), ('DOCUMENT', 'Document'), ('ELIGIBILITY', 'Eligibility'), ('PAYMENT', 'Payment'), ('UNIVERSITY_APPLICATION', 'University Application'), ('ENROLLMENT', 'Enrollment'), ('NOTE', 'Note'), ('COMPLETED', 'Completed')], db_index=True, max_length=40)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='admissions.admission')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admission_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PHOTO', 'Passport Size Photo'), ('AADHAAR', 'Aadhaar'), ('SSLC', '10th / SSLC Certificate'), ('PLUS_TWO', '12th / Plus Two Certificate'), ('UG_CERTIFICATE', 'UG Certificate'), ('PG_CERTIFICATE', 'PG Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('MIGRATION_CERTIFICATE', 'Migration Certificate'), ('MARK_SHEET', 'Mark Sheet'), ('PREVIOUS_SEMESTER', 'Previous Semester Mark Sheet'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='admissions/documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.admission')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_admission_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionFee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fee_type', models.CharField(choices=[('REGISTRATION', 'Registration Fee'), ('ADMISSION', 'Admission Fee'), ('TUITION', 'Tuition Fee'), ('EXAM', 'Exam Fee'), ('UNIVERSITY', 'University Fee'), ('PROJECT', 'Project Fee'), ('CERTIFICATE', 'Certificate Fee'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='admissions.admission')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], max_length=30)),
                ('reference_number', models.CharField(blank=True, max_length=150)),
                ('receipt_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('paid_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='admissions.admission')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_admission_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('level', models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_semesters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_credit_transfer_available', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programs', to='admissions.institution')),
            ],
            options={
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='admissions.program'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_program_per_institution'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['status', 'assigned_to'], name='admissions__status_a00f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['institution', 'status'], name='admissions__institu_59e00c_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['vertical', 'status'], name='admissions__vertica_fa2ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['channel', 'status'], name='admissions__channel_7fe471_idx'),
        ),
    ]
