# Generated by Django 5.2.17 on 2026-09-16 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        ('leads', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissiondocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='admissionfee',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['institution', 'name']},
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='unique_program_per_institution',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='completed_years_or_semesters',
        ),
        migrations.AddField(
            model_name='admission',
            name='completed_semesters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='completed_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='partners.partner'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='academic_session',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='admission',
            name='channel',
            field=models.CharField(choices=[('DIRECT', 'BEST Direct'), ('PARTNER', 'Partner')], db_index=True, default='DIRECT', max_length=20),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DOCUMENT_PENDING', 'Document Pending'), ('DOCUMENT_VERIFICATION', 'Document Verification'), ('ELIGIBILITY_PENDING', 'Eligibility Pending'), ('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('FEE_PENDING', 'Fee Pending'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied'), ('ENROLLMENT_PENDING', 'Enrollment Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=40),
        ),
        migrations.AlterField(
            model_name='admission',
            name='university_admission_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='vertical',
            field=models.CharField(choices=[('REGULAR', 'Regular Distance Education'), ('CREDIT_TRANSFER', 'Credit Transfer')], db_index=True, default='REGULAR', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissiondocument',
            name='document_type',
            field=models.CharField(choices=[('PHOTO', 'Photo'), ('AADHAAR', 'Aadhaar'), ('SSLC', 'SSLC'), ('PLUS_TWO', 'Plus Two'), ('UG_CERTIFICATE', 'UG Certificate'), ('PG_CERTIFICATE', 'PG Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('MIGRATION_CERTIFICATE', 'Migration Certificate'), ('MARK_SHEET', 'Mark Sheet'), ('PREVIOUS_SEMESTER', 'Previous Semester Document'), ('OTHER', 'Other')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='admissionfee',
            name='fee_type',
            field=models.CharField(choices=[('REGISTRATION', 'Registration'), ('ADMISSION', 'Admission'), ('TUITION', 'Tuition'), ('EXAM', 'Exam'), ('UNIVERSITY', 'University'), ('PROJECT', 'Project'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionpayment',
            name='paid_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='admissionpayment',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='institution',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='level',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('PG', 'Postgraduate'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='UG', max_length=30),
        ),
        migrations.AddIndex(
            model_name='admission',
            index=models.Index(fields=['partner', 'status'], name='admissions__partner_3a0a93_idx'),
        ),
        migrations.AddConstraint(
            model_name='program',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_institution_program'),
        ),
    ]
