# Generated by Django 5.2.17 on 2026-09-24 16:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_admissiondocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramInternalFinance',
            fields=[
                ('program', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='internal_finance', serialize=False, to='admissions.program')),
                ('center_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility_review_required',
            field=models.BooleanField(db_index=True, default=True, help_text='Keep enabled when eligibility data needs manual verification before a lead can be auto-qualified.'),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='minimum_qualification',
            field=models.CharField(choices=[('UNSPECIFIED', 'Unspecified'), ('SSLC', 'SSLC / 10th'), ('PLUS_TWO', 'Plus Two / 12th'), ('DIPLOMA', 'Diploma'), ('UG', 'Undergraduate Degree'), ('PG', 'Postgraduate Degree'), ('OTHER', 'Other')], db_index=True, default='UNSPECIFIED', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='required_stream',
            field=models.CharField(blank=True, help_text='Optional stream requirement. Use comma-separated accepted streams when structured matching is possible.', max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='study_mode',
            field=models.CharField(choices=[('DISTANCE', 'Distance'), ('ONLINE', 'Online'), ('REGULAR', 'Regular'), ('HYBRID', 'Hybrid'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=30),
        ),
        migrations.CreateModel(
            name='ProgramFeePlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Standard', max_length=120)),
                ('student_total_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exam_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('other_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='admissions.program')),
            ],
            options={
                'ordering': ['program', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProgramFeeInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_stage', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('fee_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='admissions.programfeeplan')),
            ],
            options={
                'ordering': ['fee_plan', 'installment_number'],
            },
        ),
        migrations.AddConstraint(
            model_name='programfeeplan',
            constraint=models.UniqueConstraint(fields=('program', 'name'), name='unique_program_fee_plan_name'),
        ),
        migrations.AddConstraint(
            model_name='programfeeinstallment',
            constraint=models.UniqueConstraint(fields=('fee_plan', 'installment_number'), name='unique_program_fee_installment_number'),
        ),
    ]
