# Generated by Django 5.2.17 on 2026-10-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_program_counselling_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='programfeeplan',
            name='import_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
