# Generated by Django 5.2.17 on 2026-10-05 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_programfeeplan_import_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='data_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('PARTIAL', 'Partial Data'), ('VERIFIED', 'Verified')], db_index=True, default='NEEDS_REVIEW', max_length=30),
        ),
        migrations.AddField(
            model_name='program',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='program',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='programfeeplan',
            name='data_status',
            field=models.CharField(choices=[('NEEDS_REVIEW', 'Needs Review'), ('PARTIAL', 'Partial Data'), ('VERIFIED', 'Verified')], db_index=True, default='NEEDS_REVIEW', max_length=30),
        ),
        migrations.AddField(
            model_name='programfeeplan',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='programfeeplan',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programfeeplan',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_fee_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
