# Generated by Django 5.2.17 on 2026-09-16 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_userrole'),
        ('organization', '0002_alter_department_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_role_scopes', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='business_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_role_scopes', to='organization.businessunit'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_role_scopes', to='organization.department'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='scope_type',
            field=models.CharField(choices=[('OWN', 'Own Records'), ('TEAM', 'Own Team'), ('DEPARTMENT', 'Department'), ('BRANCH', 'Branch'), ('BUSINESS_UNIT', 'Business Unit'), ('ORGANIZATION', 'Entire Organization')], default='OWN', max_length=30),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['scope_type'], name='accounts_userrole_scope_idx'),
        ),
    ]
