# Generated by Django 5.2.17 on 2026-09-23 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='overdue_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['reminder_at', 'reminder_sent_at'], name='notif_task_reminder_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['due_at', 'overdue_notified_at'], name='notif_task_overdue_idx'),
        ),
    ]
